---
- name: Play to setup apache servers
  hosts: backend_servers
  tasks:
    - debug:
        msg: "Start Apache server setup"

    - name: Setup firewall
      include_role:
        name: firewall
      vars:
        firewall_services:
          - http
        firewall_tcp_ports:
          - 8080

    - name: Setup apache server
      include_role:
        name: apache

    - debug:
        msg: "Finished Apache server setup"

