---
- name: Manage OpenStack Servers
  hosts: control
  gather_facts: false
  become: false
  collections:
    - gpte.openstack

  roles:

    - openstack_manage_inmemory_inventory

  tasks:
    - name: Gather network facts
      setup:
        gather_subset:
          - 'network'
      delegate_facts: true
      delegate_to: localhost

- name: update resolve.conf
  hosts: load_balancers,app_servers,database_servers
  become: true
  vars:
    satellite_activationkey: gpte-labs-rhel8
    satellite_org: prod
  tasks:
    - name: DNS IP updated
      lineinfile:
        state: present
        path: /etc/sysconfig/network-scripts/ifcfg-eth0
        line: "{{ item }}"
      loop:
        - PEERDNS=no
        - DNS1={{ hostvars.localhost.ansible_default_ipv4.address }}
    
    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted

    - name: install katello-ca-consumer package
      yum:
        name: http://satellite.example.com/pub/katello-ca-consumer-latest.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: register system and attach subs
      redhat_subscription:
        state: present
        activationkey: "{{ satellite_activationkey }}"
        org_id: "{{ satellite_org }}"
        auto_attach: true

    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
